'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Reflection.AssemblyTitleAttribute("MultiM II"),  _
 Assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0"),  _
 Assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Prazbid3Enterprise"),  _
 Assembly: System.Reflection.AssemblyDescriptionAttribute("MultiM,le logiciel de création de serveur Minitel,CONTINUED!!!!!!!!"),  _
 Assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0"),  _
 Assembly: System.Runtime.InteropServices.GuidAttribute("2f0b6322-8366-4d0a-a787-c790d61f2fc1"),  _
 Assembly: System.Reflection.AssemblyTrademarkAttribute("MultiM™"),  _
 Assembly: System.Reflection.AssemblyProductAttribute("MultiM II"),  _
 Assembly: System.Reflection.AssemblyCompanyAttribute("Prazbid3Enterprise"),  _
 Assembly: System.Runtime.InteropServices.ComVisibleAttribute(true)> 
